// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var LogoGif = require("../logo.gif").default;
var Config$Dogumentation = require("dogumentation/src/Config.bs.js");

var logo = LogoGif;

var config_logo = logo;

var config = {
  logo: config_logo
};

Config$Dogumentation.start(config, undefined);

exports.logo = logo;
exports.config = config;
/* logo Not a pure module */
